name: serverless deployer

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: install node
      uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
    
    - name: setup go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
    
    - name: checkout source code
      uses: actions/checkout@master

    - name: build
      run: make clean build

    - name: deploy
      uses: serverless/github-action@master
      with:
        args: deploy
      env:
        SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}