name: serverless deployer

on:
  push:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:    
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.14'
      
      - name: lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.26.0
          golangci-lint run

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:  
      - name: install go
        uses: actions/setup-go@v2
        with:
          go-version: '1.14'

      - uses: actions/checkout@v2

      - name: run tests
        run: go test ./...
  
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:    
    - name: setup go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
    
    - uses: actions/checkout@master

    - name: build
      run: make clean build

    - name: deploy
      uses: serverless/github-action@master
      with:
        args: deploy
      env:
        SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SLS_DEBUG: 1